---
job: "extension"
config:
  name: "adafac"
  process:
    - type: "diffusion_trainer"
      training_folder: "output"
      sqlite_db_path: "./aitk_db.db"
      device: "cuda"
      trigger_word: "ohwx_man"
      performance_log_every: 10
      network:
        type: "lokr"
        linear: 32
        linear_alpha: 32
        conv: 16
        conv_alpha: 16
        lokr_full_rank: true
        lokr_factor: 8
        network_kwargs:
          ignore_if_contains: []
      save:
        dtype: "bf16"
        save_every: 250
        max_step_saves_to_keep: 4
        save_format: "diffusers"
        push_to_hub: false
      datasets:
        - folder_path: "workspace/ai-toolkit/dataset"
          mask_path: null
          mask_min_value: 0.1
          default_caption: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          cache_latents_to_disk: false
          is_reg: false
          network_weight: 1
          resolution:
            - 1024
            - 512
            - 768
          controls: []
          shrink_video_to_frames: true
          num_frames: 1
          do_i2v: true
          flip_x: false
          flip_y: false
      train:
        batch_size: 1
        bypass_guidance_embedding: false
        steps: 3000
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adafactor"
        timestep_type: "weighted"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        unload_text_encoder: true
        cache_text_embeddings: false
        lr: 0.0002
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: false
        force_first_sample: false
        disable_sampling: true
        dtype: "bf16"
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: "person"
        switch_boundary_every: 1
        loss_type: "mse"
        do_differential_guidance: true
        differential_guidance_scale: 3
      model:
        name_or_path: "Tongyi-MAI/Z-Image-Turbo"
        quantize: false
        qtype: "qfloat8"
        quantize_te: false
        qtype_te: "qfloat8"
        arch: "zimage:turbo"
        low_vram: false
        model_kwargs: {}
        layer_offloading: false
        layer_offloading_text_encoder_percent: 1
        layer_offloading_transformer_percent: 1
        assistant_lora_path: "ostris/zimage_turbo_training_adapter/zimage_turbo_training_adapter_v2.safetensors"
      sample:
        sampler: "ddpm"
        sample_every: 250
        width: 1024
        height: 1024
        samples:
          - prompt: "a professional business headshot of ohwx_man wearing a light blue business shirt in a light gray gradient studio"
          - prompt: "a professional business headshot of ohwx_man wearing a white business shirt in a dark gray gradient studio"
          - prompt: "a professional business headshot of ohwx_man wearing a black sweater in a corporate blue gradient studio"
          - prompt: "a professional business headshot of ohwx_man wearing a navy blue blazer in a modern office building with large windows in the background, strong bokeh"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 1
        sample_steps: 8
        num_frames: 1
        fps: 1
meta:
  name: "[name]"
  version: "1.0"
